# Generated by Django 4.0.3 on 2022-04-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('std_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=20)),
                ('std_pwd', models.CharField(max_length=20)),
            ],
        ),
    ]
